opencollective/opencollective

docs/api/quickstart.md

Documents an error I ran into when I was getting my dev environment set up. I needed to install Graphics Magic in order for the frontend container to start up correctly.

Add troubleshooting section to quickstart; document image-to-ascii error

---

.github/stale.yml

Uses https://probot.github.io/apps/stale/ to mark inactive issues as `wontfix` after 60 days unless someone comments to keep the issue open in 7 days after the `wontfix` label is added. 
The bot will never mark `emergency`, `high priority`, `priority`, or `security` labeled issues as `wontfix`.

Add Stale[bot] configuration

---

.github/stale.yml

- Increase daysUntilState to 90
- Increase daysUntilClose to 10
- Don't run on the following labels:
- backlog: These are tasks that are programmed to do.
- bug: We should not let bugs unfixed.
- project: These are meta-tasks of things we need to do. Thay may not be active for a long period, but we still need to keep them
- technical-debt: We should not forget about these

More gentle stale bot configuration

---

.github/stale.yml

The message were saying that issue will be closed if no activity but we don't do that anymore

Remove close message from stale bot

---

BOUNTY.md

IMHO it makes more sense if you first check and adjust the issue for newbies and only later actually tag it with a bounty. Thus, you may still see that the issue is not good enough yet or so…

Change order of bug bounty tagging

---

rfcs/005-replace-downshift-by-react-select.md

- Frontend
- Don't reinvent the wheel
A lot of the code in `StyledSelect` is dedicated to re-creating a full select behaviour. For example [we catch the keyboard events](https://github.com/opencollective/opencollective-frontend/blob/aacbf4f36efe8d6ff71308252dcdcf8b9565a5a7/src/components/StyledSelect.js#L252) to navigate between items. This is time consuming to maintain and error prone.
- Improve accessibility
Whatever we do, we'll never be able to reach the level of accessibility of the native select or the one of a library with hundreds of testers and contributors.
Someone actually complained about our select component on Twitter (see [StyledSelect accessibility · Issue #2056 · opencollective/opencollective · GitHub](https://github.com/opencollective/opencollective/issues/2056))
- Add …

RFC: Replace downshift by react-select

---

SECURITY.md

The preparation of a nice security report can take time. We don't want security contributors to loose too much time preparing a report if the issue is already known. This PR changes the expectation for the initial report to state that it's ok for the initial contact to just send a summary of the issue.

Security Policy: Change expectations for initial report

---

.github/ISSUE_TEMPLATE/project.md

During the last team retreat we have defined a framework for prioritization. This pull request adds it to the `Project` issue template to enforce its usage.
Based on https://docs.opencollective.com/help/product/roadmap#key-questions-for-prioritization

IssuesTemplates: Add section about prioritization to Project

---

postmortem/2019-12-23-add-core-contributor-email-cc.md

See: https://github.com/opencollective/opencollective/blob/postmortem/2019-12-23-add-core-contributor-email-cc/postmortem/2019-12-23-add-core-contributor-email-cc.md

postmortem: Leak collective core contributors emails

---

.github/stale.yml

Often people misunderstand that our stale bot is not going to close issues. One of the reasons may be that they're used to stale bots doing it (that's the default behavior). Anyway I thought we could try to make that clear and I'd be happy to hear suggestions if anyone has a better idea.  
New message:
>   This issue has been automatically marked as stale because it has not had recent activity.
We haven't had the time to address it yet, but **we want to keep it open**. This message is just a reminder for us to help triage issues.

Try to make stalebot message clearer

---

rfcs/009-move-away-from-react-hook-form.md

See: https://github.com/opencollective/opencollective/blob/rfcs/009-move-away-from-react-hook-form/rfcs/009-move-away-from-react-hook-form.md

RFC: Move away from react-hook-form

---

BOUNTY.md

This updates the broken link that should be pointing to getting paid through Open Collective. :smile:

Update Broken Link Pointing to Submitting Expenses

---

BOUNTY.md

This replaces the teams link which is not accessible to everyone (only members of OpenCollective) in BOUNTY.md
Fixes https://github.com/opencollective/opencollective/issues/3061

Add Correct Link in BOUNTY.md

---

team/Benjamin.md

Fix minor typos found on `Followed PRs` and `Followed Issues` descriptions. 🙂

Typo Correction on Benjamin's Description

---

.github/ISSUE_TEMPLATE/documentation.md

Adding a documentation issue template that can be used when we kick off a project to ensure that the docs team are involved in the process from the start.

Add documentation issue template

---

.github/MAINTAINER_REPLY_TEMPLATES/DONT_COMMENT_ON_CLOSED_ISSUE.md
.github/MAINTAINER_REPLY_TEMPLATES/GUIDELINES_NOT_FOLLOWED.md
.github/MAINTAINER_REPLY_TEMPLATES/README.md
.github/MAINTAINER_REPLY_TEMPLATES/WRONG_FORUM_USE_SLACK.md

As per my discussion started at https://github.com/opencollective/opencollective/discussions/4308 and https://github.com/opencollective/opencollective/issues/4304#issuecomment-846712621, I just quickly created this with some standard issue reply templates. We can probably add more or alter this later as needed. 😄 
Also this is just my opinion/way of doing this; if you disagree or think that the current system in place is sufficient for now it's fine to close this and we can incorporate this kinda process later as well. I am open to ideas or suggestions. 😄

Add Some Basic Maintainer Issue Reply Templates

---

README.md
rfcs/005-replace-downshift-by-react-select.md
rfcs/009-move-away-from-react-hook-form.md

This typo is also there when we hover our mouse to the GitHub icon in the website:

Fix GitHub typos

---

rfcs/012-merge-rebase-strategy.md

This proposes a slight addition to the way we merge PRs as per the following discussion; https://opencollective.slack.com/archives/CEZUS9WH3/p1623691549000100 🐨

Propose RFC for Merging PRs 

---

.github/ISSUE_TEMPLATE/project.md

As per the discussion today this change _vastly_ reduced the overhead of creating a project issue.
I've moved a lot of the previous detail into a templates section at the end of the template `<xzibit gif/>`. the idea being that this is a more open template with minimum guidance that can be followed in the first instance and built up from there if need. 
[Diff view over here](https://github.com/opencollective/opencollective/pull/4580/commits/abbbf13fc262c47574c22b8169cc73f459133fa2?short_path=78999fc#diff-78999fcbbb99da4a9ee00336a4f8c2c90f00870b236700e583cd09cacb9c5de1)

Edit project template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-spec.md
.github/ISSUE_TEMPLATE/project.md
.github/ISSUE_TEMPLATE/user_need.md

Adds a 'user needs' template for support et al to describe problems in a way that product, design and engineering can expand as a feature spec or take on as a project.  The goal here is to be lightweight yet provide enough context to apply prioritisation criteria (impact, alignment, effort).
Also fixes some typos and amends descriptions of other templates to separate them a little.

Add user need template
