opencollective/opencollective

README.md

and to the google doc with all open source projects
+ some edits in the copy

Added links to examples of collectives

---

README.md

Move Gitter Badge top of readme

---

README.md

Result: https://github.com/OpenCollective/OpenCollective/blob/slack-badge/README.md

Add badge for Slack

---

docs/index.html

Always load Scripts and CSS from HTTPS

---

COMMUNITY-GUIDELINES.MD

This just adds a space for proper rendering of the heading.

Add a space for proper Markdown rendering

---

postmortem/2019-03-06-contributeAs-bogus-createCollective-query.md

https://github.com/opencollective/opencollective/blob/postmortem/2019-03-06-contributeAs-bogus-createCollective-query/postmortem/2019-03-06-contributeAs-bogus-createCollective-query.md

Postmortem: contributeAs bogus createCollective query

---

postmortem/2019-03-26-login-token-mismatch.md

Link to the MD file:
https://github.com/opencollective/opencollective/blob/postmortem/login-token-mismatch/postmortem/2019-03-26-login-token-mismatch.md

postmortem: Login Token Mismatch

---

rfcs/001-cutting-edge.md
rfcs/002-styled-components.md
rfcs/003-next-js.md
rfcs/deprecated/001-redesign-ledger.md
rfcs/deprecated/002-store-fees-on-user-and-collective-ledgers.md
rfcs/deprecated/003-double-entry-ledger.md
rfcs/deprecated/004-multi-currency-v2.md
rfcs/deprecated/005-libledger.md
rfcs/deprecated/README.md
rfcs/deprecated/imgs/payment-flow.svg

This PR imports all RFCs from:
- https://github.com/opencollective/opencollective-frontend
- https://github.com/opencollective/opencollective-api

Import Frontend and API RFCs

---

rfcs/006-typescript.md

If accepted, this RFC will trigger the merge of https://github.com/opencollective/opencollective-api/pull/2183.

RFC: Use Typescript on the API

---

BOUNTY.md

The file looked strange when displayed in the Github UI:

BOUNTY.md: Fix indentation

---

rfcs/006-use-react-hook-form.md

If accepted, this RFC will trigger the merge of https://github.com/opencollective/opencollective-frontend/pull/2983.

RFC: Use React Hook Form

---

rfcs/007-docker-files.md

Closes https://github.com/opencollective/opencollective/issues/2641

Add RFC for Docker files

---

rfcs/008-github-actions.md

https://github.com/opencollective/opencollective/blob/rfc/github-actions/rfcs/008-github-actions.md

rfc: use GitHub Actions for CI

---

BOUNTY.md

Follow up from https://github.com/opencollective/opencollective/pull/2467

Update core developers links

---

postmortem/2019-12-23-add-core-contributor-email-cc.md
rfcs/005-replace-downshift-by-react-select.md
rfcs/006-typescript.md
rfcs/008-github-actions.md
rfcs/009-move-away-from-react-hook-form.md

chore: fix typos

---

TOS.md

This fixes typographical problems related to the TOS.md file.
Fixes #3062

Fix Typographical Errors in TOS.md

---

rfcs/010-react-intl.md

https://github.com/opencollective/opencollective/blob/2595e4e2d73a7f34f2bef49c5c24abd2c06f1e69/rfcs/010-react-intl.md

RFC: Best Practices with react-intl

---

SECURITY.md

- Remove BackYourStack
- Add REST service

SECURITY.md: Update scope

---

rfcs/011-graphql.md

See the formatted document:
https://github.com/opencollective/opencollective/blob/graphql-best-practices/rfcs/011-graphql.md

RFC: GraphQL best practices

---

team/Alanna.md

Changes this file to type markdown and correct a hyperlink. 😄

Change Filetype to Markdown and Correct HyperLink

---

postmortem/2019-12-23-add-core-contributor-email-cc.md

Related to https://github.com/opencollective/opencollective/issues/3675

Rename `master` to `main`

---

.github/ISSUE_TEMPLATE/project.md

I’m opening this PR as a place for discussion around our project process, I’m not tied to anything in this but I do want to encourage us to think about the following:
- bringing our mission and our current focus to the fore (I beleive this was originally the point around making ourselves sustainable within a year)
- ensuring that we identify projects as the result of insight, research or feedback
- offloading some of the estimation so that we can prioritise by impact and broad appreciation of effort/complexity in the first instance
- expadning the process to include documentation and marketing/comm's from the start
I would also like to add something here about feedback processes, but I'll open an issue for this as I am not sure we have an established standard process for this, but it …

Project process proposal

---

team/Alanna.md
team/Benjamin.md
team/Sudharaka.md

This adds a brief bio about myself and corrects some typos I found. 😄

Add brief bio and fix some typos

---

.github/ISSUE_TEMPLATE/project.md

Add project risk to kick off area

---

rfcs/012-git-signed-commits.md

Something I was thinking over the weekend and thought of opening this RFC to discuss. 😉

Suggest Signing of Commits for Git for Core Developers

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-spec.md
.github/ISSUE_TEMPLATE/ideas--irritations-and-needs.md
.github/ISSUE_TEMPLATE/project.md
.github/ISSUE_TEMPLATE/release-.md

* add release template
* rename 'needs' template
* modify project template to explicitly use documentation and release templates

Update issue templates

---

product/pitches/Basic Funding Dashboard.md

Update Basic Funding Dashboard.md

---

postmortem/2023-02-02-non-recorded-credit-card-transactions.md

https://github.com/opencollective/opencollective/blob/znarf-patch-4/postmortem/2023-02-02-non-recorded-credit-card-transactions.md

Post Mortem: non recorded credit card transactions

---

.github/ISSUE_TEMPLATE/bug_report.md

Adding semicolons to bug template

---

postmortem/2023-04-04-transactions-null-indexes.md

https://github.com/opencollective/opencollective/blob/postmortem/2023-04-04-transactions-null-indexes/postmortem/2023-04-04-transactions-null-indexes.md

Add postmortem/2023-04-04-transactions-null-indexes.md

---

SECURITY.md

Remove CVS3 scores from security policy
